### ISSUE TITLE
IllegalArgumentException: Unknown header type

### ISSUE THREAD

**Issue by enp** [aboutsip/pkts#85] opened 2018-02-25 17:54 UTC
Hi,

I tried to read pcap file by this code:

```
#!/usr/bin/env groovy

@Grab('io.pkts:pkts-core:3.+')

import io.pkts.Pcap

Pcap pcap = Pcap.openStream('/tmp/icmp.pcap')
```

and got error:

```
Caught: java.lang.IllegalArgumentException: Unknown header type
java.lang.IllegalArgumentException: Unknown header type
        at io.pkts.frame.PcapGlobalHeader.parse(PcapGlobalHeader.java:207)
        at io.pkts.Pcap.openStream(Pcap.java:123)
        at io.pkts.Pcap.openStream(Pcap.java:152)
        at io.pkts.Pcap.openStream(Pcap.java:163)
        at io.pkts.Pcap$openStream.call(Unknown Source)
        at icmp.run(icmp.groovy:7)
```
File is valid:

```
$ tshark -r /tmp/icmp.pcap 
    1   0.000000    127.0.0.1 → 127.0.0.1    ICMP 98 Echo (ping) request  id=0x55be, seq=1/256, ttl=64
    2   0.000013    127.0.0.1 → 127.0.0.1    ICMP 98 Echo (ping) reply    id=0x55be, seq=1/256, ttl=64 (request in 1)
```
So, why I can't read it?

**Comment by jonbo372** [comment] 2018-03-13 22:39
Hi,

Thanks for reporting. Could you send me the pcap you used? Send it to jonas@jonasborjesson.com

**Comment by igaoliang** [comment] 2018-03-23 03:11
emmmm. the same problem .

Exception in thread "main" java.lang.IllegalArgumentException: Unknown header type
	at io.pkts.frame.PcapGlobalHeader.parse(PcapGlobalHeader.java:207)
	at io.pkts.Pcap.openStream(Pcap.java:123)
	at io.pkts.Pcap.openStream(Pcap.java:152)
	at io.pkts.Pcap.openStream(Pcap.java:163)
	at PcapTestKt.analysisPcap(PcapTest.kt:17)
	at PcapTestKt.main(PcapTest.kt:12)

**Comment by aboutsip** [comment] 2018-03-24 07:53
Please send me a pcap that doesn't work so I can take a look at it. Certainly seems like you are using a newer format that I myself has, so far, no need for and as such there is no support for it. Also make sure that you didn't specify compression since I don't support that right now.

Pull requests are welcome!

**Comment by igaoliang** [comment] 2018-03-26 01:22
ok. my test case and the pcap file is here.

http://note.youdao.com/noteshare?id=0a0f2dc01798d82a49e74e8b2afc84ce

**Comment by aboutsip** [comment] 2018-03-26 05:02
Hi,

So the file you sent me is indeed in the next generation pcap (pcap-ng) format, which pkts.io do not support at this moment. Please ensure to save in the old pcap format. Issue 86 is tracking this so I'm closing this as a duplicate of that one.

**Closed by aboutsip** 2018-03-26 05:02 UTC

**Comment by lavanyasundararajan** [comment] 2019-04-10 06:21
I also face the same issue Unknown header type I have sent the .pcap file to jonas@jonasborjesson.com
